/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy.view;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import pharmacy.controller.BatchController;
import pharmacy.controller.DrugController;
import pharmacy.controller.InvoiceController;
import pharmacy.controller.RackController;
import pharmacy.controller.SupplierController;
import pharmacy.model.Batch;
import pharmacy.model.Drug;
import pharmacy.model.Rack;
import pharmacy.model.Supplier;

/**
 *
 * @author Chamil123
 */
public class GRN extends javax.swing.JPanel {

    private String drug_id;

    /**
     * Creates new form addCenter
     */
    public GRN() {
        initComponents();

        jPanel2.setVisible(false);
        jScrollPane6.setVisible(false);
        jTable10.setVisible(false);

        jPanel3.setVisible(false);
        jScrollPane7.setVisible(false);
        jTable11.setVisible(false);

      
        
//        int getMaxId = GrnController.getMaxId();
//            String formatted = String.format("%06d", getMaxId);
//            jLabel4.setText("" + formatted);

    }

    public void tablePaymentTotal() {
        DecimalFormat df = new DecimalFormat("##.00");
        DefaultTableModel tb1 = (DefaultTableModel) jTable1.getModel();
        int rowCount = jTable1.getRowCount();
        double totalPayment = 0;
        double totalDiscount = 0;
        double disAmount = 0;

        System.out.println("aaaa : " + rowCount);
        for (int i = 0; i < rowCount; i++) {
            double quantity = Double.parseDouble(tb1.getValueAt(i, 3).toString());
            double price = Double.parseDouble(tb1.getValueAt(i, 4).toString());
            double discount = Double.parseDouble(tb1.getValueAt(i, 5).toString());

            double totAmount = quantity * price;
            disAmount += (totAmount * discount) / 100;

            totalPayment += Double.parseDouble(tb1.getValueAt(i, 6).toString());
            totalDiscount += Double.parseDouble(tb1.getValueAt(i, 5).toString());
        }
        double discount = 0;
        if (!jTextField11.getText().equals("")) {
            discount = Double.parseDouble(jTextField11.getText());
        } else {
            discount = 0;
        }
        double payAmount = 0;
        if (!jTextField12.getText().equals("")) {
            payAmount = Double.parseDouble(jTextField12.getText());
        } else {
            payAmount = 0;
        }
        jLabel7.setText("" + df.format(totalPayment).toString());
        jLabel81.setText("" + totalDiscount);
        jLabel79.setText("" + disAmount);

        double mainDiscount = (totalPayment * discount) / 100;
        jLabel9.setText("" + df.format(totalPayment - mainDiscount).toString());

        jLabel82.setText("" + df.format(payAmount - (totalPayment - mainDiscount)).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 239, 244));
        setMaximumSize(new java.awt.Dimension(1150, 590));
        setMinimumSize(new java.awt.Dimension(1150, 590));
        setPreferredSize(new java.awt.Dimension(1150, 590));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Customer registration");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, 29));

        jLabel2.setText("GRN Number :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 99, 30));

        jLabel3.setText("Supplier Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 78, -1));

        jTextField1.setBackground(new java.awt.Color(255, 204, 102));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 270, 32));

        jTable11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable11.setRowHeight(20);
        jTable11.getTableHeader().setReorderingAllowed(false);
        jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable11MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable11MousePressed(evt);
            }
        });
        jTable11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable11KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable11KeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(jTable11);
        if (jTable11.getColumnModel().getColumnCount() > 0) {
            jTable11.getColumnModel().getColumn(1).setMinWidth(200);
            jTable11.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable11.getColumnModel().getColumn(2).setMinWidth(50);
            jTable11.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 188, 460, 170));

        jTable10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable10.setRowHeight(20);
        jTable10.getTableHeader().setReorderingAllowed(false);
        jTable10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable10MousePressed(evt);
            }
        });
        jTable10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable10KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable10KeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(jTable10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 270, 30));

        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField2.setEnabled(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, 30));

        jLabel4.setText("Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 99, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Drug ID", "Drgu Name", "Expire Date", "Quantity", "Price", "Discount", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(1).setMinWidth(300);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, 1070, 160));

        jTextField3.setBackground(new java.awt.Color(255, 204, 102));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 158, 300, 33));

        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 100, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 90, 30));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 70, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("0.00");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 380, 180, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Sub Total :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 90, 25));

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(51, 51, 51));
        jLabel78.setText("Total Line Dis %");
        jPanel1.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 0, 153));
        jLabel80.setText("Total Line Dis Amount");
        jPanel1.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, -1, -1));

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel79.setText("0.00");
        jPanel1.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 110, -1));

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel81.setText("0.00");
        jPanel1.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("0.00");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 230, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel10.setText("Total : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, -1, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 153));
        jTextField12.setText("0");
        jTextField12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField12FocusGained(evt);
            }
        });
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 180, 40));

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(0, 0, 255));
        jLabel85.setText("Amount                       :");
        jPanel1.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 160, -1));

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(0, 0, 255));
        jLabel84.setText("Discount rate  %        :");
        jPanel1.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField11FocusGained(evt);
            }
        });
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 411, 180, 30));

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 0, 153));
        jLabel83.setText("Change");
        jPanel1.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 500, 90, -1));

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 0, 0));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel82.setText("0.00");
        jPanel1.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 220, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("  [Esc]  Cash");
        jRadioButton1.setFocusPainted(false);
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("  [F6] Cheque");
        jRadioButton2.setFocusPainted(false);
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("  [F7] Credit");
        jRadioButton3.setFocusPainted(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 130, 30));

        jLabel13.setText("Quantity");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jLabel14.setText("Discount");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        jLabel15.setText("Expire Date");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 80, -1));

        jLabel11.setText("View Customers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(0, 845, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable10MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jTable10.getModel();
        int row = jTable10.getSelectedRow();
        String centerId = dtm.getValueAt(row, 1).toString();

        System.out.println("asdasd: " + centerId);

        ProductBatch dialog = new ProductBatch(new javax.swing.JFrame(), true, centerId);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_jTable10MouseClicked

    private void jTable10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable10MousePressed

    }//GEN-LAST:event_jTable10MousePressed

    private void jTable10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable10KeyPressed
        if (evt.getKeyCode() == 10) {
            try {

                int Row = jTable10.getSelectedRow();
                jTextField1.setText(jTable10.getValueAt(Row, 0).toString());
                String drug_id = jTable10.getValueAt(Row, 0).toString();

                String unitPrice = jTable10.getValueAt(Row, 1).toString();

                jPanel2.setVisible(false);
                jScrollPane6.setVisible(false);
                jTable10.setVisible(false);

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_jTable10KeyPressed

    private void jTable10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable10KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable10KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == 40) {
            if (jTextField1.getText().length() != 0) {
                jTable10.grabFocus();
                ListSelectionModel selectionModel = jTable10.getSelectionModel();
                selectionModel.setSelectionInterval(0, 0);
            } else {
                jPanel2.setVisible(false);
                jScrollPane6.setVisible(false);
                jTable10.setVisible(false);
            }

        } else if (evt.getKeyCode() == 27) {
            jRadioButton1.setSelected(true);
            jTextField12.grabFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jTable10.getModel();

        if (jTextField1.getText().trim().length() != 0) {
            try {
                List<Supplier> supplier = SupplierController.searchSupplierByName(jTextField1.getText().trim());

                dtm.setRowCount(0);

                if (supplier != null) {
                    for (int i = 0; i < supplier.size(); i++) {

                        Vector v = new Vector();
                        v.add(supplier.get(i).getSup_name());
                        v.add(supplier.get(i).getSup_companyName());

                        dtm.addRow(v);
                        jPanel2.setVisible(true);
                        jScrollPane6.setVisible(true);
                        jTable10.setVisible(true);

                    }

                    if (dtm.getRowCount() == 0) {
                        jPanel2.setVisible(false);
                        jScrollPane6.setVisible(false);
                        jTable10.setVisible(false);
                    } else {
                        jPanel2.setVisible(true);
                        jScrollPane6.setVisible(true);
                        jTable10.setVisible(true);
                    }
                }
                supplier = null;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateInvoice.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CreateInvoice.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            dtm.setRowCount(0);
            jPanel2.setVisible(false);
            jScrollPane6.setVisible(false);
            jTable10.setVisible(false);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTable11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable11MouseClicked

    private void jTable11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable11MousePressed

    private void jTable11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable11KeyPressed
        if (evt.getKeyCode() == 10) {
            try {

                int Row = jTable11.getSelectedRow();
                jTextField3.setText(jTable11.getValueAt(Row, 0).toString());
                drug_id = jTable11.getValueAt(Row, 2).toString();

                Drug drug = DrugController.searchByDrugId(drug_id);
                jLabel5.setText(drug.getDrug_generic_name());

                Batch batch = BatchController.getOldBatch(drug.getDrug_id());
                jLabel6.setText("" + batch.getBatch_unit_price());

                jPanel3.setVisible(false);
                jScrollPane7.setVisible(false);
                jTable11.setVisible(false);

                jTextField5.grabFocus();

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_jTable11KeyPressed

    private void jTable11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable11KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable11KeyReleased

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if (evt.getKeyCode() == 40) {
            if (jTextField3.getText().length() != 0) {
                jTable11.grabFocus();
                ListSelectionModel selectionModel = jTable11.getSelectionModel();
                selectionModel.setSelectionInterval(0, 0);
            } else {
                jPanel3.setVisible(false);
                jScrollPane7.setVisible(false);
                jTable11.setVisible(false);
            }

        } else if (evt.getKeyCode() == 27) {
            jRadioButton1.setSelected(true);
            jTextField12.grabFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jTable11.getModel();

        if (jTextField3.getText().trim().length() != 0) {
            try {
                List<Drug> drug = DrugController.searchDrugByName(jTextField3.getText().trim());

                dtm.setRowCount(0);

                if (drug != null) {
                    for (int i = 0; i < drug.size(); i++) {

                        Vector v = new Vector();
                        v.add(drug.get(i).getDrug_name());
                        v.add(drug.get(i).getDrug_generic_name());
                        v.add(drug.get(i).getDrug_id());

                        dtm.addRow(v);
                        jPanel3.setVisible(true);
                        jScrollPane7.setVisible(true);
                        jTable11.setVisible(true);

                    }

                    if (dtm.getRowCount() == 0) {
                        jPanel3.setVisible(false);
                        jScrollPane7.setVisible(false);
                        jTable11.setVisible(false);
                    } else {
                        jPanel3.setVisible(true);
                        jScrollPane7.setVisible(true);
                        jTable11.setVisible(true);
                    }
                }
                drug = null;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateInvoice.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CreateInvoice.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            dtm.setRowCount(0);
            jPanel3.setVisible(false);
            jScrollPane7.setVisible(false);
            jTable11.setVisible(false);
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        jTextField4.grabFocus();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        jDateChooser2.grabFocus();

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
//        DefaultTableModel tb1 = (DefaultTableModel) jTable1.getModel();
//
//        double Price = Double.parseDouble(jLabel6.getText());
//        double amount = Double.parseDouble(jTextField5.getText());
//        double discount = Double.parseDouble(jTextField4.getText());
//        double itemAmount = Price * amount;
//
//        double disAmount = (discount * itemAmount) / 100;
//
//        double itemamountMinusDis = itemAmount - disAmount;
//
//        Vector v = new Vector();
//        v.add(drug_id);
//        v.add(jTextField3.getText());
//        v.add(jTextField5.getText());
//        v.add(jLabel6.getText());
//        v.add(jTextField4.getText());
//        v.add(itemamountMinusDis);
//        tb1.addRow(v);
//        tablePaymentTotal();
////
////        tablePaymentTotal();
////
//        drug_id = "";
////        unitPrice = "";
////
//        jTextField3.setText("");
//        jLabel5.setText("");
//        jTextField5.setText("");
//        jTextField4.setText("0");
//        jLabel6.setText("");
//        jTextField3.grabFocus();

    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusGained
        jTextField12.selectAll();
    }//GEN-LAST:event_jTextField12FocusGained

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        jRadioButton1.setSelected(true);
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        jRadioButton1.setSelected(true);
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        if (evt.getKeyCode() == 27) {
            jRadioButton1.setSelected(true);
            jTextField12.grabFocus();
        }
        DecimalFormat df = new DecimalFormat("##.00");
        jLabel82.setText(jTextField12.getText());

        double payment = 0;
        if (!jTextField12.getText().equals("")) {
            payment = Double.parseDouble(jTextField12.getText());
        } else {
            payment = 0;
        }

        double total = Double.parseDouble(jLabel7.getText());
        double balance = payment - total;
        jLabel82.setText("" + df.format(balance).toString());
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped

    }//GEN-LAST:event_jTextField12KeyTyped

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusGained
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField11FocusGained

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed

        //        DecimalFormat df = new DecimalFormat("00.00");
        //
        //        double netVal = Double.parseDouble(jLabel17.getText());
        //        double discRate = Double.parseDouble(jTextField3.getText());
        //        setNetDisc = netVal * discRate / 100;
        //        jLabel40.setText(df.format(setNetDisc).toString());
        //        double totalLineDisc = Double.parseDouble(jLabel37.getText());
        //        totalDiscAmount = setNetDisc + totalLineDisc;
        //        jLabel42.setText(df.format(totalDiscAmount).toString());
        //        jLabel31.setText(df.format(tot - totalDiscAmount).toString());
        //        jTextField7.grabFocus();
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed

        if (evt.getKeyCode() == 116) {
            jRadioButton1.setSelected(true);
            //   jTextField8.setText("Cash");
            jTextField3.grabFocus();
        } else if (evt.getKeyCode() == 117) {
            jRadioButton2.setSelected(true);
            //   jTextField8.setText("Cheque");
            jTextField3.grabFocus();
        } else if (evt.getKeyCode() == 118) {
            jRadioButton3.setSelected(true);
            //  jTextField8.setText("Credit");
            jTextField3.grabFocus();
        } else if (evt.getKeyCode() == 27) {
            jRadioButton1.setSelected(true);
            jTextField12.grabFocus();
        }
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        DecimalFormat df = new DecimalFormat("##.00");
        // double payment = Double.parseDouble(jLabel77.getText());
        double discount = 0;
        if (!jTextField11.getText().equals("")) {
            discount = Double.parseDouble(jTextField11.getText());
        } else {
            discount = 0;
        }
        double payAmount = 0;
        if (!jTextField12.getText().equals("")) {
            payAmount = Double.parseDouble(jTextField12.getText());
        } else {
            payAmount = 0;
        }
        //        double discount = Double.parseDouble(jTextField11.getText());
//        double disAmount = (payment * discount) / 100;
//        jLabel7.setText("" + df.format(payment - disAmount).toString());
//        jLabel82.setText("" + df.format(payAmount - (payment - disAmount)).toString());
    }//GEN-LAST:event_jTextField11KeyReleased

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        System.out.println(evt.getKeyCode());

    }//GEN-LAST:event_jTextField11KeyTyped

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        if (evt.getKeyCode() == 27) {
            jRadioButton1.setSelected(true);
            jTextField12.grabFocus();
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        if (evt.getKeyCode() == 27) {
            jRadioButton1.setSelected(true);
            jTextField12.grabFocus();
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
       
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tb1 = (DefaultTableModel) jTable1.getModel();

        double Price = Double.parseDouble(jLabel6.getText());
        double amount = Double.parseDouble(jTextField5.getText());
        double discount = Double.parseDouble(jTextField4.getText());
        double itemAmount = Price * amount;

        double disAmount = (discount * itemAmount) / 100;

        double itemamountMinusDis = itemAmount - disAmount;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date dt1 = jDateChooser2.getDate();
        String stringdate1 = sdf.format(dt1);

        Vector v = new Vector();
        v.add(drug_id);
        v.add(jTextField3.getText());
        v.add(stringdate1);
       
        v.add(jTextField5.getText());
        v.add(jLabel6.getText());
        v.add(jTextField4.getText());
        v.add(itemamountMinusDis);
        tb1.addRow(v);
        tablePaymentTotal();
//
//        tablePaymentTotal();
//
        drug_id = "";
//        unitPrice = "";
//
        jTextField3.setText("");
        jLabel5.setText("");
        jTextField5.setText("");
        jTextField4.setText("0");
        jLabel6.setText("");
        jTextField4.setText("");
       
        //jDateChooser2.set
        jTextField3.grabFocus();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
